services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
    networks:
      - nn-network
    volumes: 
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    #command: --innodb-use-native-aio=0
    container_name: mysql_db
    restart: always
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodeappdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nn-network
    tty: true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nn-network

networks:
  nn-network:
    driver: bridge

