FROM node:18 AS builder

WORKDIR /usr/src/app

COPY . .

RUN npm install
RUN npm install mysql
RUN npm install express -y --save

FROM node:18-alpine3.19
WORKDIR /usr/src/app

ENV DOCKERIZE_VERSION v0.8.0

RUN apk update --no-cache \
    && apk add --no-cache wget openssl \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apk del wget
COPY --from=builder /usr/src/app .

ENTRYPOINT [ "node", "index.js" ]